### ISSUE TITLE
ThreadException

### ISSUE THREAD

**Issue by haniokasai** [E-DevPM/Hydracon#12]
i made phar http://jenkins.haniokasai.com/job/Hydracon-PMMP/3/console
but

Fatal error: Uncaught ClassNotFoundException: Class ThreadException not found in /var/lib/jenkins/workspace/Hydracon-PMMP/src/spl/BaseClassLoader.php:144
Stack trace:
#0 [internal function]: BaseClassLoader->loadClass('ThreadException')
#1 /var/lib/jenkins/workspace/Hydracon-PMMP/src/pocketmine/command/CommandReader.php(70): spl_autoload_call('ThreadException')
#2 /var/lib/jenkins/workspace/Hydracon-PMMP/src/pocketmine/PocketMine.php(502): pocketmine\command\CommandReader->quit()

**Comment by yesitswalid** [comment]
Thanks for your report please use src for now
