### ISSUE TITLE
Golden Apple Regeneration

### ISSUE THREAD

**Issue by daniel022302** [E-DevPM/Hydracon#28]
When you a Golden Apple it only regens you for like 2 hearts, and it's slow

**Comment by TheAz928** [comment]
Enchanted golden apple or just golden apple?

**Comment by daniel022302** [comment]
Just golden apple

**Comment by TheAz928** [comment]
Just golden apple has lower regeneration so it's not a bug I guess...

**Comment by daniel022302** [comment]
But can you still fix it?

**Comment by yesitswalid** [comment]
setAmplifier(3); Az make commit

**Comment by TheAz928** [comment]
Okay @daniel022302 I'll fix it
